### login
POST localhost:3000/api/losgin
Content-Type: application/json

{
    "email": "lo_cherguelaine@esi.dz",
}


### hello
POST  http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "email": "lala@esi.dz",
    "password": "11221122"
}
